language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r install/requirements.txt
  - npm install jshint

# command to run tests
script:
  - pep8 .
  - jshint . --exclude ./node_modules
