language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - "pip install -r install/requirements.txt"
  - sudo apt-get install nodejs npm
  - sudo ln -s /usr/bin/nodejs /usr/bin/node

# command to run tests
script:
  - pep8 gateway/
  - pep8 project316/
