language: python
#test using these versions of python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r scripts/requirements.txt
  - npm install jshint

# setup mysql
before_script:
  - mysql -e 'create database gateway;'
  - mysqladmin -u root password "root"

# command to run tests
script:
  - pep8 .
  - jshint . --exclude ./node_modules
  - coverage run --source gateway manage.py test

after_success:
  - coveralls
