language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r scripts/requirements.txt
  - npm install jshint
  - mysqladmin -u root password "root"

# command to run tests
script:
  - pep8 .
  - jshint . --exclude ./node_modules
  - python manage.py test
